chore(notifee): replacing `react-native-push-notification` with `@notifee/react-native`
platformbuilders/use-notifications pull request #133
Opened 2022-07-24 18:36 UTC by ammichael

## Descrição do PR

- Substituição da `react-native-push-notification` pela [@notifee/react-native](https://notifee.app/react-native/docs/overview)
- Expondo novo método de `getFCMToken`

## Tipo de mudança

- [X] Nova feature (mudança non-breaking que adiciona uma funcionalidade)
- [ ] Bug fix (mudança non-breaking que conserta um problema)
- [X] Breaking change (ajuste ou funcionalidade que pode causar uma quebra numa funcionalidade já existente)

## Checklist 🚨

- [X] Meu código segue o code style da Builders
- [X] Testado usando Yalc

2022-07-25 12:40 UTC, duspada approved these changes

2022-07-25 12:40 UTC, duspada commented on package.json
> +    "@notifee/react-native": "^5.5.0",
se tirar ela de peer, e deixar em dependencies, vc nao precisa colocar ela em devdependencies e a pessoa não precisa instalar...
certo?

2022-07-25 13:04 UTC, fabinppkbuilders reviewed
OBS: Se eu só instalo as dependências ele acaba pegando as ultimas versões e acaba não buildando no ios.
Com a v15.2.0 dá ruim.

![Captura de Tela 2022-07-25 às 10 00 24](https://user-images.githubusercontent.com/84453168/180783482-4d0d11ec-cefe-479c-be07-706c6cbe4f55.png)

![Captura de Tela 2022-07-25 às 10 03 52](https://user-images.githubusercontent.com/84453168/180783892-787f94c3-1eda-4257-aece-133adaba8e92.png)

Acredito que resolve fixando a versão atual.

2022-07-25 13:37 UTC, luancurti commented on package.json
> +    "@notifee/react-native": "^5.5.0",
Na minha visão deveria estar em `dependencias` visto que algo específico para essa biblioteca

2022-07-25 13:43 UTC, luancurti commented on package.json
> +    "@notifee/react-native": "^5.5.0",
Se formos manter assim teria que ter algo na documentação falando que tem que instalar a biblioteca

2022-07-25 13:58 UTC, luancurti commented on src/configureNotifications.ts
> +  onNotification = async () => {},
Não entendi o pq da mudança para `async`

2022-07-25 14:05 UTC, luancurti commented
> OBS: Se eu só instalo as dependências ele acaba pegando as ultimas versões e acaba não buildando no ios. Com a v15.2.0 dá ruim.
> 
> ![Captura de Tela 2022-07-25 às 10 00 24](https://user-images.githubusercontent.com/84453168/180783482-4d0d11ec-cefe-479c-be07-706c6cbe4f55.png)
> 
> ![Captura de Tela 2022-07-25 às 10 03 52](https://user-images.githubusercontent.com/84453168/180783892-787f94c3-1eda-4257-aece-133adaba8e92.png)
> 
> Acredito que resolve fixando a versão atual.

@fabinppkbuilders imagino que se vc remover a pasta `Pods` e remover o arquivo `Podfile.lock` e rodar o script `npx pod-install` dentro da pasta `ios` deve funcionar, pois aqui foi de boa

2022-07-25 14:07 UTC, luancurti requested changes
Abrindo `Request Changes` pois estou terminando de testar, para garantir que não vai mergear enquanto termino os testes e os questionamentos

2022-07-25 17:51 UTC, luancurti commented on src/configureNotifications.ts
> +    console.log('LOG: ~ remoteMessage', remoteMessage);
Esse log vai ficar mesmo?

2022-07-26 12:18 UTC, fabinppkbuilders commented on src/configureNotifications.ts
> +    console.log('LOG: ~ remoteMessage', remoteMessage);
Hoje já existem esses logs e não vejo problemas em continuar mantendo eles. Até que ajudam :)

2022-07-26 12:18 UTC, fabinppkbuilders commented
@luancurti tentei substituir a lib interna da voltz pelo nossa e mesmo dando um yarn clean ele apontou aquela flag e não buildou.
Talvez seja algo dentro da Voltz 🤷‍♂️

2022-07-26 14:19 UTC, luancurti commented
Android validado usando o template

https://user-images.githubusercontent.com/7242605/181028988-0bdabf5f-046a-4c74-a844-4207f81f5efb.mp4

2022-07-27 17:47 UTC, fabinppkbuilders commented
@luancurti Vai validar IOS ou já aprovar?

obs: top a evidência do android 👌

2022-08-12 00:22 UTC, merged

2022-08-12 00:22 UTC, ammichael commented
Dei uma mãozada aqui para dar continuidade, e tenho usado num app pessoal e tá rolando como deveria